/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import {
  VirtualNode,
} from './components/scb-list/scb-list-interfaces';

import {
  StencilComponent as ScbList
} from './components/scb-list/scb-list';

declare global {
  interface HTMLScbListElement extends ScbList, HTMLElement {
  }
  var HTMLScbListElement: {
    prototype: HTMLScbListElement;
    new (): HTMLScbListElement;
  };
  interface HTMLElementTagNameMap {
    "scb-list": HTMLScbListElement;
  }
  interface ElementTagNameMap {
    "scb-list": HTMLScbListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "scb-list": JSXElements.ScbListAttributes;
    }
  }
  namespace JSXElements {
    export interface ScbListAttributes extends HTMLAttributes {
      addClass?: string;
      addClassEven?: string;
      addClassOdd?: string;
      bindToList?: boolean;
      bottomOffset?: number;
      itemAs?: string;
      items?: object[];
      template?: VirtualNode;
      wrapperClass?: string;
    }
  }
}

